### ISSUE TITLE
Running evo/h5evolve_sample.py

### ISSUE THREAD

**Issue by WardF** [HDFGroup/H5Tuner#4]
Are there instructions for using the `h5evolve_sample.py` script? I'm not finding anything on the wiki, but currently when I try to run the python script I encounter indentation errors.

**Comment by hdffede** [comment]
Double checking that the tuner is loaded via LD_PRELOAD when you run h5evolve sample
Is the issue at the xml?
I'll look into replicate the issue.

**Comment by WardF** [comment]
Let me take a look at this before you dive into it; I'll follow up here with my results. Thanks for confirming that it *should* be working :)
